{"name": "Успешное изменение данных авторизованного пользователя", "status": "failed", "statusDetails": {"message": "AssertionError: assert 403 == 200\n +  where 403 = <Response [403]>.status_code", "trace": "self = <tests.test_user.TestUser object at 0x000002E82241C6D0>, create_user = ({'email': 'nsrtq@yandex.ru', 'name': 'akwfqgezth', 'password': 'wcdobhblne'}, <Response [200]>)\n\n    @allure.title('Успешное изменение данных авторизованного пользователя')\n    @allure.description('Проверка: статус 200, данные успешно меняются и возвращаются в ответе.')\n    def test_update_user_with_auth(self, create_user):\n        user_data, response_post = create_user\n        token = response_post.json()['accessToken']\n    \n        # Обновление данных пользователя\n        new_data = {\n            \"email\": generate_user_data()['email'],\n            \"name\": generate_user_data()['name']\n        }\n    \n        response = requests.patch(f\"{url.MAIN_URL}/api/auth/user\", headers={\"Authorization\": f\"Bearer {token}\"}, json=new_data)\n    \n>       assert response.status_code == 200\nE       assert 403 == 200\nE        +  where 403 = <Response [403]>.status_code\n\ntests\\test_user.py:22: AssertionError"}, "description": "Проверка: статус 200, данные успешно меняются и возвращаются в ответе.", "start": 1724871116313, "stop": 1724871116721, "uuid": "f0857e51-d488-4bf7-af09-d3bd7af7cc0c", "historyId": "b9c80aaa483972bf0d25e5fd428db5e2", "testCaseId": "b9c80aaa483972bf0d25e5fd428db5e2", "fullName": "tests.test_user.TestUser#test_update_user_with_auth", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user"}, {"name": "subSuite", "value": "TestUser"}, {"name": "host", "value": "LAPTOP-74V5TFPG"}, {"name": "thread", "value": "16640-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user"}]}