{"name": "Логин с неверным логином и паролем", "status": "passed", "description": "Проверка:статус 401, сообщение об ошибке о некорректных данных.", "start": 1724871100352, "stop": 1724871102490, "uuid": "9a9d2f43-27ef-43db-910b-f0874cf4e2aa", "historyId": "666e64f1f50108a6aa8ce0b6292b7625", "testCaseId": "666e64f1f50108a6aa8ce0b6292b7625", "fullName": "tests.test_login_user.TestLoginUser#test_login_with_incorrect_credentials", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "LAPTOP-74V5TFPG"}, {"name": "thread", "value": "16640-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}